version: '3.8'

services:
  # 1. MySQL 主库 (专门负责写)
  mysql-master:
    image: mysql:8.0
    container_name: mysql-master
    ports:
      - "3306:3306" # 主库用默认的 3306 端口
    environment:
      - MYSQL_ROOT_PASSWORD=root  # 统一把密码设为 root，方便测试
      - MYSQL_DATABASE=seckill_db # 启动时自动创建我们需要的数据库
    volumes:
      - ./mysql/master/my.cnf:/etc/mysql/conf.d/my.cnf
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  # 2. MySQL 从库 (专门负责读)
  mysql-slave:
    image: mysql:8.0
    container_name: mysql-slave
    ports:
      - "3307:3306" # 从库映射到电脑的 3307 端口，防止冲突
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./mysql/slave/my.cnf:/etc/mysql/conf.d/my.cnf
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  # 3. Redis (顺便把后勤也用 Docker 管起来，以后再也不用手动开黑窗口了)
  redis:
    image: redis:latest
    container_name: my-redis
    ports:
      - "6379:6379"

  # （注意：我们先把 Java 和 Nginx 暂时注释掉或拿掉，专注把数据库的底层打通！）