worker_processes  1;

events {
    worker_connections  1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    # 【负载均衡】
    # 定义两台后端的 Java 服务器，一会我们会用 Docker 启动它们，分别在 8080 端口
    upstream backend_servers {
        server backend1:8080; 
        server backend2:8080;
    }

    server {
        listen       80;
        server_name  localhost;

        # 【动静分离 - 静态部分】
        # 当用户请求根目录（或者 product.html）时，Nginx 直接从自己的 html 目录返回静态文件
        location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm product.html;
        }

        # 【动静分离 - 动态部分 & 负载均衡】
        # 当用户请求包含 /api/ 的路径时，Nginx 把它转发给上面定义的 backend_servers
        location /api/ {
            proxy_pass http://backend_servers;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}